#!/usr/bin/env python3

def main():
    # Prompt the user for a question in the console
    user_input = input("Ask a question: ")
    if user_input is None:
        print("No input received.")
        return
    question = user_input.strip()
    if question == "":
        print("No question provided.")
        return
    # Simple deterministic response for demonstration
    print(f"You asked: {question}")
    print("Response: This is a demo console application generated by app.py.")

if __name__ == "__main__":
    main()
